title: My Blog Title
author: Dude McDudeson
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Just a test site for learning purposes.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  gdellaceca # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
